### PR TITLE
Optimize `create_extra_permissions`

### PR DESCRIPTION
**Pull request by illia-v**
`create_extra_permissions` tries to create a permission eight times for every model every time `./manage.py migrate` is used.
In a project with a big number of models this process can take more than a minute.

This update minimizes the number of SQL queries by:
* selecting all needed content types at once;
* selecting information about existing relevant permissions to a set that is used to check for existence of a permission before trying to create it;
* creating permissions using `bulk_create`.

`./manage.py migrate` runs 9 times faster with this change in my case when no new migrations are applied.

### CODE REVIEW

**Comment by saxix** [comment]
@illia-v thanks for the PR, can you lint the code? I'll merge it just after that.

**Comment by illia-v** [comment]
@saxix done. I'm sorry for that error.

**Comment by illia-v** [comment]
BTW, Django emits [`post_migrate`](https://docs.djangoproject.com/en/3.2/ref/signals/#post-migrate) for every application with the `models` module.
Therefore, `create_extra_permissions` can be executed multiple times while `./manage.py migrate` is running. Selecting models of one specific app in the function can be another optimization.

**Comment by saxix** [comment]
@illia-v sorry the late reply - sadly I do not have much time this period, I'll ckeck this asap and back to you end of this week

**Review by domdinicola — APPROVED** [review]

**Comment by domdinicola** [comment]
@illia-v can you please rebase the PR

**Comment by illia-v** [comment]
@domdinicola thanks for your review and merging the changes. Do you know if there is a schedule for a new release?

**Comment by domdinicola** [comment]
I guess December, in order to release a version compatible with Django 4.0

**Pull request merged**
