### PR TITLE
By rows update action

### PR DESCRIPTION
**Pull request by trepmag**
Hello, I'm proposing an action which allow to edit selected model instances in a rows layout form.

The following admin options allow to choose which fields must appear in the form:
- adminactions_byrows_update_fields
- adminactions_byrows_update_exclude

Hope it can be of some use.

### CODE REVIEW

**Comment by saxix** [comment]
I like the idea. Can you rebase on develop and fix the tests ? I'll be happy to merge then.

**Comment by trepmag** [comment]
Yes, I need to adapt code against django version 1.4 (is working against 1.7); will try that.

**Comment by trepmag** [comment]
I could refactor code to be django >= 1.4 compatible.

Now, there's are some other tests that fail in tests/test_exports.py with the following message:
BadDataError: ('django.contrib.auth.models.User', IntegrityError('UNIQUE constraint failed: auth_user.username',))

But is triggered with django 1.4 (not 1.8). Also, I notice that if I run each test files separately the failures doesn't happens...

If you have any idea...

**Comment by saxix** [comment]
I'm thinking to remove support for django<1.6 in the next release, so probably we can ignore these issues. By the way which database are you using ?

**Comment by trepmag** [comment]
Then, just run tests successfully under django 1.6.

PS: Using sqlite (as defined in demo settings)

**Pull request merged**
